version: '3.8'
name: serengueti

networks:
  serengueti-network:
    driver: bridge

services:
  mongo-express:
    container_name: mongo-express
    depends_on:
      - reservation-mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_SERVER=reservation-mongodb
    hostname: mongo-express
    image: mongo-express:latest
    networks:
      - serengueti-network
    ports:
      - "${ME_CONFIG_PORT}:8081"

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:alpine
    networks:
      - serengueti-network
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  notification-mongodb:
    container_name: notification-mongodb
    environment:
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    hostname: notification-mongodb
    image: mongo:latest
    networks:
      - serengueti-network
    volumes:
      - notification_mongodb_data:/data/db

  notification-redis:
    container_name: notification-redis
    hostname: notification-redis
    image: redis:alpine
    networks:
      - serengueti-network
    volumes:
      - notification_redis_data:/data

  notification-service:
    build: ./microservices/notification-service
    container_name: notification-service
    depends_on:
      - notification-mongodb
      - notification-redis
    env_file:
      - ./microservices/notification-service/.env
    hostname: notification-service
    networks:
      - serengueti-network
    volumes:
      - ./microservices/notification-service:/app

  redis-insight:
    container_name: redis-insight
    hostname: redis-insight
    image: redislabs/redisinsight:latest
    networks:
      - serengueti-network
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db

  reservation-mongodb:
    container_name: reservation-mongodb
    environment:
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    hostname: reservation-mongodb
    image: mongo:latest
    networks:
      - serengueti-network
    volumes:
      - reservation_mongodb_data:/data/db

  reservation-redis:
    container_name: reservation-redis
    hostname: reservation-redis
    image: redis:alpine
    networks:
      - serengueti-network
    volumes:
      - reservation_redis_data:/data

  reservation-service:
    build: ./microservices/reservation-service
    container_name: reservation-service
    depends_on:
      - reservation-mongodb
      - reservation-redis
    env_file:
      - ./microservices/reservation-service/.env
    hostname: reservation-service
    networks:
      - serengueti-network
    volumes:
      - ./microservices/reservation-service:/app

volumes:
  notification_mongodb_data:
  notification_redis_data:
  reservation_mongodb_data:
  reservation_redis_data:
  redis_insight_data:
