version: '3.8'
name: serengueti
services:
  reservation-service:
    hostname: reservation-service
    container_name: reservation-service
    build: ./microservices/reservation-service
    volumes:
      - ./microservices/reservation-service:/app
    env_file:
      - ./microservices/reservation-service/.env
    networks:
      - serengueti-network

  notification-service:
    hostname: notification-service
    container_name: notification-service
    build: ./microservices/notification-service
    volumes:
      - ./microservices/notification-service:/app
    env_file:
      - ./microservices/notification-service/.env
    networks:
      - serengueti-network

  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - serengueti-network

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    networks:
      - serengueti-network

  mongo-express:
    hostname: mongo-express
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - "${ME_CONFIG_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - serengueti-network

volumes:
  mongodb_data:

networks:
  serengueti-network:
    driver: bridge
